# https://github.com/helm/charts
apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceInstance
metadata:
  name: simple-service-db
spec:
  clusterServiceClassExternalName: postgresql
  clusterServicePlanExternalName: 9-6-2
---
apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceBinding
metadata:
  name: simple-service-db-binding
spec:
  instanceRef:
    name: simple-service-db
